# Generated by Django 5.1.4 on 2024-12-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_assignment_user_alter_exam_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="Not started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="Not started",
                max_length=20,
            ),
        ),
    ]
