# Generated by Django 5.1.4 on 2024-12-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_assignment_status_exam_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
