# Generated by Django 5.1.4 on 2024-12-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_assignment_status_alter_exam_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="status",
        ),
    ]
