# Generated by Django 5.1.4 on 2024-12-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
